Here I am going to copy and paste a number of potential/related interview questions that I have seen throughout my research for interview prep. The idea here is pretty intuitive. Starting somewhere, building memory, and comfort attacking these types of problems.

# Pythonic kind of math
## - *Given an array_of_ints, find the highest_product you can get from three of the integers.*

    
At first, I assumed this would be easy: just sort the list/array of integers in descending order and multiply the first three. However this is naive as it doesn't take into account the possibility of negative numbers. Now it will be a bit more complex! 

In [2]:
array_of_ints = [-9, 2, 5, 6, -9, 8]

My first try:

In [24]:
def highest_product_of_3(array):
    sorted_ints = sorted(array)
    biggest_abs = []
    for num in sorted_ints:
        if abs(sorted_ints[num]) > abs(sorted_ints[num + 1]):
            biggest_abs.append(sorted_ints[num])
        else:
            break
    return (biggest_abs)


In [25]:
highest_product_of_3(array_of_ints)

IndexError: list index out of range

researched... heapq module has a convenient tool for this: 'smallest' and 'largest'. Although sorting the list could be just as easy, I have the feeling that would increase the runtime/Big O notation.

In [3]:
import heapq

In [4]:
def highest_product_of_3(nums): 
    max3 = heapq.nlargest(3, nums)
    min3 = heapq.nsmallest(3, nums)
    a1 = max3[0] * max3[1] * max3[2]
    a2 = min3[0] * min3[1] * min3[2]
    a3 = min3[0] * max3[0] * max3[1]
    a4 = min3[0] * min3[1] * max3[0]
    if abs(min(a1, a2, a3, a4)) > abs(max(a1, a2, a3, a4)):
        return min(a1, a2, a3, a4)
    else:
        return max(a1, a2, a3, a4)

O(n) solution

In [5]:
highest_product_of_3(array_of_ints)

648

works!

# Create a function to count duplicate numbers in a list:

In [9]:
a = [1, 4, 2, 9, 7, 4, 3, 3, 9, 8, 9, 3, 1]


def count_duplicates(a):
    duplicates = []
    for num in a:
        if a.count(num) > 1: 
            duplicates.append(num)
    return duplicates
            

count_duplicates(a)

[1, 4, 9, 4, 3, 3, 9, 9, 3, 1]

Ok, so that returned us every number AND it's duplicate. I think we just want a count of duplicates. Need to work more on this!

# math kind of math

## - If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

This could be done using list comprehension

In [1]:
sum([i for i in range(1000) if i % 3 == 0 or i % 5 == 0])

233168

## Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [24]:
def fib(num):
    fib1, fib2 = 0, 1
    while fib1 < num:
        yield fib1
        fib1, fib2 = fib2, fib1 + fib2
        
print(sum(filter(lambda n: n % 2 == 0, fib(4000000))))
        

4613732


# Hackerrank problems
____
*Polar coordinates*

Polar coordinates are an alternative way of representing Cartesian coordinates or Complex Numbers.

A complex number  Capture.PNG

is completely determined by its real part  and imaginary part .
Here,  is the imaginary unit.
A polar coordinate () Capture.PNG

is completely determined by modulus  and phase angle .

If we convert complex number  to its polar coordinate, we find:
: Distance from  to origin, i.e., 
: Counter clockwise angle measured from the positive -axis to the line segment that joins  to the origin.

Python's cmath module provides access to the mathematical functions for complex numbers.


This tool returns the phase of complex number  (also known as the argument of ).

>>> phase(complex(-1.0, 0.0))
3.1415926535897931

This tool returns the modulus (absolute value) of complex number .

>>> abs(complex(-1.0, 0.0))
1.0
Task
You are given a complex . Your task is to convert it to polar coordinates.

Input Format

A single line containing the complex number . Note: complex() function can be used in python to convert the input as a complex number.

Constraints

Given number is a valid complex number

Output Format

Output two lines:
The first line should contain the value of .
The second line should contain the value of .

Sample Input

  1+2j
Sample Output

 2.23606797749979 
 1.1071487177940904
Note: The output should be correct up to 3 decimal places.

In [7]:
import cmath

In [1]:
z = complex(input())

1+2j


In [5]:
z

(1+2j)

In [9]:
print(cmath.polar(z), '\n')

(2.23606797749979, 1.1071487177940904) 



____
ABC is a right triangle,  at 90'.
Therefore, .

Point M is the midpoint of hypotenuse.

You are given the lengths AB and BC.
Your task is to find  (angle , as shown in the figure) in degrees.

Input Format

The first line contains the length of side AB.
The second line contains the length of side BC.

Output Format

Output  in degrees.

Note: Round the angle to the nearest integer.

Examples:
If angle is 56.5000001°, then output 57°.
If angle is 56.5000000°, then output 57°.
If angle is 56.4999999°, then output 56°.


In [15]:
import math

In [34]:
AB = int(input())
BC = int(input())

10
10


First, we need to find length of AC, the hypotenuse

In [21]:
hyp = math.sqrt((AB**2) + (BC**2))
hyp

14.142135623730951

In [26]:
hypo = math.hypot(AB, BC)
hypo

14.142135623730951

In [30]:
math.acos(BC/hypo)

0.7853981633974484

Below is the complete workaround from one of the discussion comments."We can Solve this problem by using a property: ** That a median on the hypotenuse divides the right angled triangle in two isosceles triangles.** * Means AM=BM=CM * So, ∡MBC = ∡MCB"

In [35]:
print(str(int(round(math.degrees(math.atan2(AB,BC)))))+'°')

45°


____

For an input consisting of N number of commands and their actual commands, write a code that iterates through each input for a list. This will require parsing input phrases such as "insert 0 5" and "append 6". solution courtesy of nice guy in discussion.

In [64]:
if __name__ == '__main__':
    N = int(input())   
    
    commands = {
        "insert": lambda mylist, i, e: mylist.insert(i, e),
        "append": lambda mylist, e: mylist.append(e),
        "print": lambda mylist: print(mylist),
        "remove": lambda mylist, e: mylist.remove(e),
        "sort": lambda mylist: mylist.sort(),
        "pop": lambda mylist: mylist.pop(),
        "reverse": lambda mylist: mylist.reverse()
    }
    
    mylist = []
    
    for command in range(N):
        cmd, *args = input().split()
        args = [int(a) for a in args]
        commands[cmd](mylist, *args)     #*args is important here. the asterisk denotes our variable number of arguments

12
insert 0 5
insert 1 8
append 8
remove 5
print
[8, 8]
pop
append 4
insert 2 3
remove 4
print
[8, 3]
insert 4 20
print
[8, 3, 20]


write up for * in python https://www.geeksforgeeks.org/args-kwargs-python/

____

## Task
Given an integer,n , and  space-separated integers as input, create a tuple, t , of those  integers. Then compute and print the result of hash(t).

Note: hash() is one of the functions in the __builtins__ module, so it need not be imported.

Input Format

The first line contains an integer, n , denoting the number of elements in the tuple.
The second line contains n space-separated integers describing the elements in tuple 't'.

Output Format

Print the result of hash(t)

Sample Input 

2 

1 2

Sample Output 

3713081631934410656

In [59]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())

2 
1 2


In [60]:
t = tuple(integer_list)
t

(1, 2)

In [61]:
hash(t)

3713081631934410656

______


## Strings

Task

You are given a string *S*.
Your task is to find out if the string *S* contains: alphanumeric characters, alphabetical characters, digits, lowercase and uppercase characters.

Input Format

A single line containing a string *S*.

Constraints


Output Format

In the first line, print True if *S* has any alphanumeric characters. Otherwise, print False.
In the second line, print True if *S* has any alphabetical characters. Otherwise, print False.
In the third line, print True if *S* has any digits. Otherwise, print False.
In the fourth line, print True if *S* has any lowercase characters. Otherwise, print False.
In the fifth line, print True if *S* has any uppercase characters. Otherwise, print False.

My notes: Originally I completely overlooked a very key work here: "any". If "any" signifies we will need to iterate through each letter in the input. Going to try a for-loop.

In [4]:
if __name__ == '__main__':
    s = input()

    
print(any(x.isalnum() for x in s))
print(any(x.isalpha() for x in s))
print(any(x.isdigit() for x in s))
print(any(x.islower() for x in s))
print(any(x.isupper() for x in s))


qA2
True
True
True
True
True


CORRECT!

____

# NumPy

*dot*

The dot tool returns the dot product of two arrays.

import numpy

A = numpy.array([ 1, 2 ])
B = numpy.array([ 3, 4 ])

print numpy.dot(A, B)       #Output : 11

*cross*

The cross tool returns the cross product of two arrays.

import numpy

A = numpy.array([ 1, 2 ])
B = numpy.array([ 3, 4 ])

print numpy.cross(A, B)     #Output : -2
Task

You are given two arrays  and . Both have dimensions of X.
Your task is to compute their matrix product.

Input Format

The first line contains the integer N.
The next  lines contains N space separated integers of array A.
The following  lines contains N space separated integers of array B.

Output Format

Print the matrix multiplication of  and .

Sample Input

2 

1 2

3 4

1 2

3 4

Sample Output

[[ 7 10]

 [15 22]]

In [5]:
import numpy as np

In [22]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[1, 2],[3, 4]])
print(np.dot(A,B))

[[ 7 10]
 [15 22]]


In [7]:
print(np.cross(A, B))

-2


In [15]:
matrix_prod = np.matmul(A,B)
matrix_prod

11

Wording of question was a bit confusing... Sounded like "next lines contain 2 space separated integers of array A"

In [20]:
N = int(input())
A = np.array([input().split() for number in range(N)], int)
B = np.array([input().split() for number in range(N)], int)
matrix_prod = np.dot(A,B)
print(matrix_prod)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# EASY problems